spring:
  jpa:
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  datasource:
    url: jdbc:h2:mem:motiion
    username: SA
    password:
    driver-class-name: org.h2.Driver
motiion:
  domain-specific-language:
    field-config-parameters:
      - initial-field: Order Number
        field-type: INTEGER
        destination-field: orderId
      - initial-field: ${Year}-${Month}-${Day}
        field-type: DATE
        destination-field: orderDate
      - initial-field: Product Number
        field-type: STRING
        destination-field: productId
      - initial-field: Product Name
        field-type: STRING
        destination-field: productName
      - initial-field: Count
        field-type: BIGDECIMAL
        destination-field: quantity
      - initial-field: default=kg
        field-type: STRING
        destination-field: unit
